CREATE DATABASE INDIA_BOX_OFFICE;
USE INDIA_BOX_OFFICE;

SELECT * FROM BOXOFFICE;
SELECT * FROM DIRECTOR;
SELECT * FROM GENRE;
SELECT * FROM LANGUAGE;

# 1) Write a query to get Total films released? 
SELECT COUNT(*) TTL_FILMS FROM BOXOFFICE;

# 2) Write a query to get Total budget? 
SELECT SUM(BUDGET) TTL_BUDGET FROM BOXOFFICE;

# 3) Write a query to get Total worldwide collection? 
SELECT SUM(WORLDWIDE_COLLECTION) TTL_WORLDWIDE_COLLECTION FROM BOXOFFICE;

# 4) Write a query to get Total First day collection worldwide? 
SELECT SUM(FIRST_DAY_COLLECTION_WORLDWIDE) TTL_FIRSTDAY_COLLECTION FROM BOXOFFICE;

# 5) Write a query to get Total Overseas collection? 
SELECT SUM(OVERSEAS_COLLECTION) TTL_OVERSEAS_COLLECTION FROM BOXOFFICE;

# 6) Write a query to get Total India Gross collection? 
SELECT SUM(INDIA_GROSS_COLLECTION) TTL_INDIA_GROSS_COLLECTION FROM BOXOFFICE;

# 7) Top 10 films based on world wide collections. Display films, collections.
SELECT TITLE, WORLDWIDE_COLLECTION FROM BOXOFFICE ORDER BY WORLDWIDE_COLLECTION DESC LIMIT 10;

# 8) Total Number of films released by year.
SELECT YEAR, COUNT(TITLE) TTL_FILMS FROM BOXOFFICE GROUP BY YEAR ORDER BY YEAR; 

# 9) Top 10 films based on india collections. Display films, collections. 
SELECT TITLE, INDIA_GROSS_COLLECTION FROM BOXOFFICE ORDER BY INDIA_GROSS_COLLECTION DESC LIMIT 10;

# 10) Top 10 films based on overseas collections. Display films, collections. 
SELECT TITLE, OVERSEAS_COLLECTION FROM BOXOFFICE ORDER BY OVERSEAS_COLLECTION DESC LIMIT 10;

# 11) Top 10 films based on firstday collections. Display films, collections. 
SELECT TITLE, FIRST_DAY_COLLECTION_WORLDWIDE FROM BOXOFFICE ORDER BY FIRST_DAY_COLLECTION_WORLDWIDE DESC LIMIT 10;

# 12) Weekday wise films released. Display week name and number of films released. 
SELECT WEEK_NAME, COUNT(TITLE) TTL_FILMS FROM BOXOFFICE GROUP BY WEEK_NAME;

# 13) Write a query to get OTT platform wise movies count 
SELECT OTT_PLATFORM, COUNT(TITLE) TTL_FILMS FROM BOXOFFICE GROUP BY OTT_PLATFORM ORDER BY TTL_FILMS DESC;

# 14) Top 10 Directors by films released 
SELECT A.DIRECTOR, COUNT(B.TITLE) TTL_FILMS FROM DIRECTOR A JOIN BOXOFFICE B ON A.DIRECTORID = B.DIRECTORID 
GROUP BY A.DIRECTOR ORDER BY TTL_FILMS DESC LIMIT 10;

# 15) Top 10 directors by world wide collection 
SELECT A.DIRECTOR, SUM(B.WORLDWIDE_COLLECTION) TTL_WORLDWIDE_COLLECTION FROM DIRECTOR A JOIN BOXOFFICE B ON A.DIRECTORID = B.DIRECTORID 
GROUP BY A.DIRECTOR ORDER BY TTL_WORLDWIDE_COLLECTION DESC LIMIT 10;

# 16) Top 10 lead actors by world wide collection
SELECT LEAD_ACTOR_ACTRESS, SUM(WORLDWIDE_COLLECTION) TTL_WORLDWIDE_COLLECTION FROM BOXOFFICE 
GROUP BY LEAD_ACTOR_ACTRESS ORDER BY TTL_WORLDWIDE_COLLECTION DESC LIMIT 10;

# 17) Top 10 movies by IMDb rating 
SELECT TITLE, IMDB_RATING FROM BOXOFFICE ORDER BY IMDB_RATING DESC LIMIT 10;

# 18) Bottom 10 movies by IMDb rating 
SELECT TITLE, IMDB_RATING FROM BOXOFFICE ORDER BY IMDB_RATING ASC LIMIT 10;

# 19) Write a query to get 5 longest run time movies 
SELECT TITLE, RUNTIME_MINS FROM BOXOFFICE ORDER BY RUNTIME_MINS DESC LIMIT 5;

# 20) Write a query to get 5 shortest run time movies 
SELECT TITLE, RUNTIME_MINS FROM BOXOFFICE ORDER BY RUNTIME_MINS ASC LIMIT 5;

# 21) Top 7 movies by world wide collection in Bollywood 
SELECT TITLE, WORLDWIDE_COLLECTION FROM BOXOFFICE WHERE INDUSTRY = 'Bollywood' ORDER BY WORLDWIDE_COLLECTION DESC LIMIT 7;

# 22) Top 7 movies by world wide collection in Tollywood 
SELECT TITLE, WORLDWIDE_COLLECTION FROM BOXOFFICE WHERE INDUSTRY = 'Tollywood' ORDER BY WORLDWIDE_COLLECTION DESC LIMIT 7;

# 23) Top 7 movies by world wide collection in Kollywood 
SELECT TITLE, WORLDWIDE_COLLECTION FROM BOXOFFICE WHERE INDUSTRY = 'Kollywood' ORDER BY WORLDWIDE_COLLECTION DESC LIMIT 7;

# 24) Top 7 movies by world wide collection in Sandalwood 
SELECT TITLE, WORLDWIDE_COLLECTION FROM BOXOFFICE WHERE INDUSTRY = 'Sandalwood' ORDER BY WORLDWIDE_COLLECTION DESC LIMIT 7;

# 25) Top 7 movies by world wide collection in Mollywood 
SELECT TITLE, WORLDWIDE_COLLECTION FROM BOXOFFICE WHERE INDUSTRY = 'Mollywood' ORDER BY WORLDWIDE_COLLECTION DESC LIMIT 7;

# 26) Write query to display industry and verdict wise films count 
SELECT INDUSTRY, VERDICT, COUNT(TITLE) TTL_FILMS FROM BOXOFFICE GROUP BY INDUSTRY, VERDICT ORDER BY INDUSTRY;

# 27) Write query to get films based on budget in Bollywood 
SELECT TITLE, BUDGET FROM BOXOFFICE WHERE INDUSTRY = 'Bollywood' ORDER BY BUDGET DESC;

# 28) Write query to get films based on budget in Tollywood 
SELECT TITLE, BUDGET FROM BOXOFFICE WHERE INDUSTRY = 'Tollywood' ORDER BY BUDGET DESC;

# 29) Write query to get films based on budget in Kollywood
SELECT TITLE, BUDGET FROM BOXOFFICE WHERE INDUSTRY = 'Kollywood' ORDER BY BUDGET DESC;

# 30) Write query to get films based on budget in Sandalwood   
SELECT TITLE, BUDGET FROM BOXOFFICE WHERE INDUSTRY = 'Sandalwood' ORDER BY BUDGET DESC;

# 31) Write query to get films based on budget in Mollywood 
SELECT TITLE, BUDGET FROM BOXOFFICE WHERE INDUSTRY = 'Mollywood' ORDER BY BUDGET DESC;

# 32) Top 5 movies by IMDb rating from Bollywood 
SELECT TITLE, IMDB_RATING FROM BOXOFFICE WHERE INDUSTRY = 'Bollywood' ORDER BY IMDB_RATING DESC LIMIT 5;

# 33) Top 5 movies by IMDb rating from Kollywood 
SELECT TITLE, IMDB_RATING FROM BOXOFFICE WHERE INDUSTRY = 'Kollywood' ORDER BY IMDB_RATING DESC LIMIT 5;

# 34) Top 5 movies by IMDb rating from Tollywood 
SELECT TITLE, IMDB_RATING FROM BOXOFFICE WHERE INDUSTRY = 'Tollywood' ORDER BY IMDB_RATING DESC LIMIT 5;

# 35) Top 5 movies by IMDb rating from Sandalwood 
SELECT TITLE, IMDB_RATING FROM BOXOFFICE WHERE INDUSTRY = 'Sandalwood' ORDER BY IMDB_RATING DESC LIMIT 5;

# 36) Top 5 movies by IMDb rating from Mollywood 
SELECT TITLE, IMDB_RATING FROM BOXOFFICE WHERE INDUSTRY = 'Mollywood' ORDER BY IMDB_RATING DESC LIMIT 5;

# 37) Write a query to get language wise budget? 
SELECT A.LANGUAGE, SUM(B.BUDGET) TTL_BUDGET FROM LANGUAGE A JOIN BOXOFFICE B ON A.LANGUAGEID = B.LANGUAGEID
GROUP BY A.LANGUAGE ORDER BY A.LANGUAGE;

# 38) Write a query to get language wise how many directors are there? 
SELECT A.LANGUAGE, COUNT(B.DIRECTORID) DIRECTOR_CNT FROM LANGUAGE A JOIN BOXOFFICE B ON A.LANGUAGEID = B.LANGUAGEID
GROUP BY A.LANGUAGE ORDER BY A.LANGUAGE;

# 39) Write a query to get language wise worldwide total collection? 
SELECT A.LANGUAGE, SUM(B.WORLDWIDE_COLLECTION) WORLDWIDE_COLLECTION FROM LANGUAGE A JOIN BOXOFFICE B ON A.LANGUAGEID = B.LANGUAGEID
GROUP BY A.LANGUAGE ORDER BY A.LANGUAGE;

# 40) Write a query to get language, lead actor/actress wise films they acted? 
SELECT A.LANGUAGE, B.LEAD_ACTOR_ACTRESS, GROUP_CONCAT(B.TITLE ORDER BY B.TITLE SEPARATOR ', ') FILMS_LIST
FROM LANGUAGE A JOIN BOXOFFICE B ON A.LANGUAGEID = B.LANGUAGEID GROUP BY A.LANGUAGE, B.LEAD_ACTOR_ACTRESS;

SELECT A.LANGUAGE, B.LEAD_ACTOR_ACTRESS, B.TITLE FROM LANGUAGE A JOIN BOXOFFICE B ON A.LANGUAGEID = B.LANGUAGEID 
ORDER BY A.LANGUAGE, B.LEAD_ACTOR_ACTRESS;

# 41) Write a query to get language, year wise films released? 
SELECT A.LANGUAGE, B.YEAR, B.TITLE FROM LANGUAGE A JOIN BOXOFFICE B ON A.LANGUAGEID = B.LANGUAGEID 
ORDER BY A.LANGUAGE, B.YEAR;

# 42) Write a query to get films which was not released on overseas? 
SELECT TITLE FROM BOXOFFICE WHERE OVERSEAS_COLLECTION = 0;

# 43) Write a query to get language wise top 3 longest runtime moves? 
SELECT * FROM (SELECT A.LANGUAGE, B.TITLE, B.RUNTIME_MINS, RANK() OVER(PARTITION BY A.LANGUAGE ORDER BY RUNTIME_MINS DESC) AS RNK FROM
LANGUAGE A JOIN BOXOFFICE B ON A.LANGUAGEID = B.LANGUAGEID) A WHERE RNK <= 3;

# 44) Write a query to get language wise bottom 5 shortest runtime moves? 
SELECT * FROM (SELECT A.LANGUAGE, B.TITLE, B.RUNTIME_MINS, RANK() OVER(PARTITION BY A.LANGUAGE ORDER BY B.RUNTIME_MINS ASC) AS RNK FROM
LANGUAGE A JOIN BOXOFFICE B ON A.LANGUAGEID = B.LANGUAGEID) A WHERE RNK <= 5;

# 45) Write a query to get language wise top 5 films based first day collections?
SELECT * FROM (SELECT A.LANGUAGE, B.TITLE, B.FIRST_DAY_COLLECTION_WORLDWIDE, 
RANK() OVER(PARTITION BY A.LANGUAGE ORDER BY B.FIRST_DAY_COLLECTION_WORLDWIDE DESC) AS RNK
FROM LANGUAGE A JOIN BOXOFFICE B ON A.LANGUAGEID = B.LANGUAGEID) A WHERE RNK <= 5;

# 46) Write a query to get language wise top 5 films based India gross collections?
SELECT * FROM (SELECT A.LANGUAGE, B.TITLE, B.INDIA_GROSS_COLLECTION, 
RANK() OVER(PARTITION BY A.LANGUAGE ORDER BY B.INDIA_GROSS_COLLECTION DESC) AS RNK
FROM LANGUAGE A JOIN BOXOFFICE B ON A.LANGUAGEID = B.LANGUAGEID) A WHERE RNK <= 5;

# 47) Write a query to get language, Director wise films count?  ***there are multiple director values too
SELECT A.LANGUAGE, B.DIRECTOR, A.FILMS_CNT FROM
(SELECT A.LANGUAGE, B.DIRECTORID, COUNT(TITLE) FILMS_CNT FROM LANGUAGE A JOIN BOXOFFICE B ON A.LANGUAGEID = B.LANGUAGEID
GROUP BY A.LANGUAGE, B.DIRECTORID) A JOIN DIRECTOR B ON A.DIRECTORID = B.DIRECTORID ORDER BY A.LANGUAGE, B.DIRECTOR;

# 48) Write a query to get language wise OTT platform wise films count? 
SELECT * FROM (SELECT A.LANGUAGE, B.OTT_PLATFORM, COUNT(TITLE) FILMS_CNT FROM LANGUAGE A JOIN BOXOFFICE B 
ON A.LANGUAGEID = B.LANGUAGEID GROUP BY A.LANGUAGE, B.OTT_PLATFORM) A ORDER BY A.LANGUAGE, A.OTT_PLATFORM;

# 49) What are top 10 films based on language and first day collection? 
SELECT * FROM (SELECT B.LANGUAGE, A.FIRST_DAY_COLLECTION_WORLDWIDE, A.TITLE, 
RANK() OVER(PARTITION BY B.LANGUAGE ORDER BY A.FIRST_DAY_COLLECTION_WORLDWIDE DESC) AS RNK 
FROM BOXOFFICE A JOIN LANGUAGE B ON A.LANGUAGEID = B.LANGUAGEID) A WHERE RNK <= 10;

# 50) Write a query to get director wise number of films released in from year 2017 to 2019.
SELECT A.DIRECTOR, COUNT(B.TITLE) FILMS_CNT FROM DIRECTOR A JOIN BOXOFFICE B ON A.DIRECTORID = B.DIRECTORID 
WHERE B.YEAR BETWEEN 2017 AND 2019 GROUP BY A.DIRECTOR ORDER BY A.DIRECTOR;

# 51) Write a query to get director wise world wide collections? 
SELECT A.DIRECTOR, SUM(B.WORLDWIDE_COLLECTION) TTL_WORLDWIDE_COLLECTION FROM DIRECTOR A JOIN BOXOFFICE B 
ON A.DIRECTORID = B.DIRECTORID GROUP BY A.DIRECTOR ORDER BY A.DIRECTOR;

# 52) Write a query to get director wise first day world wide collections? 
SELECT A.DIRECTOR, SUM(B.FIRST_DAY_COLLECTION_WORLDWIDE) TTL_FIRSTDAY_COLLECTION FROM DIRECTOR A JOIN BOXOFFICE B 
ON A.DIRECTORID = B.DIRECTORID GROUP BY A.DIRECTOR ORDER BY A.DIRECTOR;

# 53) Write a query to get director wise India gross collections?  
SELECT A.DIRECTOR, SUM(B.INDIA_GROSS_COLLECTION) TTL_INDIA_GROSS_COLLECTION FROM DIRECTOR A JOIN BOXOFFICE B 
ON A.DIRECTORID = B.DIRECTORID GROUP BY A.DIRECTOR ORDER BY A.DIRECTOR;

# 54) Write a query to get director wise overseas collections? 
SELECT A.DIRECTOR, SUM(B.OVERSEAS_COLLECTION) TTL_OVERSEAS_COLLECTION FROM DIRECTOR A JOIN BOXOFFICE B 
ON A.DIRECTORID = B.DIRECTORID GROUP BY A.DIRECTOR ORDER BY A.DIRECTOR;

# 55) Write a query to get director, lead actor/actress and number of films? 
SELECT A.DIRECTOR, B.LEAD_ACTOR_ACTRESS, COUNT(B.TITLE) FILMS_CNT FROM DIRECTOR A JOIN BOXOFFICE B 
ON A.DIRECTORID = B.DIRECTORID GROUP BY A.DIRECTOR, B.LEAD_ACTOR_ACTRESS ORDER BY A.DIRECTOR, B.LEAD_ACTOR_ACTRESS;

# 56) Write a query to get films which is having budget on between 150 crores and 277 crores?
SELECT TITLE, BUDGET FROM BOXOFFICE WHERE BUDGET BETWEEN 150 AND 277 ORDER BY BUDGET;

# 57) Write a query to get director, week name wise films released? 
SELECT A.DIRECTOR, B.WEEK_NAME, COUNT(B.TITLE) FILMS_CNT FROM DIRECTOR A JOIN BOXOFFICE B ON A.DIRECTORID = B.DIRECTORID
GROUP BY A.DIRECTOR, B.WEEK_NAME ORDER BY A.DIRECTOR, B.WEEK_NAME;

# 58) Write a query to get OTT platform and director wise films released? 
SELECT B.OTT_PLATFORM, A.DIRECTOR, COUNT(B.TITLE) FILMS_CNT FROM DIRECTOR A JOIN BOXOFFICE B ON A.DIRECTORID = B.DIRECTORID 
GROUP BY B.OTT_PLATFORM, A.DIRECTOR ORDER BY B.OTT_PLATFORM, A.DIRECTOR;

# 59) Write a query to get director wise films released on Friday only? 
SELECT A.DIRECTOR, COUNT(B.TITLE) FILMS_CNT FROM DIRECTOR A JOIN BOXOFFICE B ON A.DIRECTORID = B.DIRECTORID
WHERE B.WEEK_NAME = 'Friday' GROUP BY A.DIRECTOR ORDER BY A.DIRECTOR;

# 60) Write a query to get films based on IMDb rating between 6.5 and 7.7? 
SELECT TITLE, IMDB_RATING FROM BOXOFFICE WHERE IMDB_RATING BETWEEN 6.5 AND 7.7 ORDER BY IMDB_RATING;

# 61) Write a query to get director, films and IMDb ratings? 
SELECT A.DIRECTOR, B.TITLE, B.IMDB_RATING FROM DIRECTOR A JOIN BOXOFFICE B ON A.DIRECTORID = B.DIRECTORID
ORDER BY A.DIRECTOR, B.TITLE;

# 62) Write a query to get films with highest budget based flop verdict? 
SELECT TITLE, BUDGET FROM BOXOFFICE WHERE VERDICT = 'Flop' ORDER BY BUDGET DESC;

# 63) Write a query to get total number of directors? 
SELECT COUNT(DIRECTORID) TTL_DIRECTORS FROM DIRECTOR;

# 64) Write a query to get verdict wise total films released? 
SELECT VERDICT, COUNT(TITLE) TTL_FILMS FROM BOXOFFICE GROUP BY VERDICT ORDER BY VERDICT;

# 65) Write a query to get top 10 directors based on number of films? 
SELECT A.DIRECTOR, COUNT(B.TITLE) TTL_FILMS FROM DIRECTOR A JOIN BOXOFFICE B ON A.DIRECTORID = B.DIRECTORID
GROUP BY A.DIRECTOR ORDER BY TTL_FILMS DESC LIMIT 10;

# 66) Write a query to get top 5 directors based on world wide collections and also industry wise?
SELECT * FROM (SELECT B.INDUSTRY, A.DIRECTOR, SUM(B.WORLDWIDE_COLLECTION) TTL_WW_COLLECTION, RANK() OVER(PARTITION BY INDUSTRY ORDER BY 
SUM(B.WORLDWIDE_COLLECTION) DESC) AS RNK FROM DIRECTOR A JOIN BOXOFFICE B ON A.DIRECTORID = B.DIRECTORID GROUP BY B.INDUSTRY,
A.DIRECTOR) A WHERE RNK <= 5;

# 67) Write a query to get top 3 directors based on India gross collections in Bollywood industry?
SELECT A.DIRECTOR, SUM(B.INDIA_GROSS_COLLECTION) TTL_IG_COLLECTION FROM DIRECTOR A JOIN BOXOFFICE B ON A.DIRECTORID = B.DIRECTORID
WHERE INDUSTRY = 'Bollywood' GROUP BY A.DIRECTOR ORDER BY TTL_IG_COLLECTION DESC LIMIT 3;

# 68) Write a query to get top 3 directors based on India gross collections in Tollywood industry?
SELECT A.DIRECTOR, SUM(B.INDIA_GROSS_COLLECTION) TTL_IG_COLLECTION FROM DIRECTOR A JOIN BOXOFFICE B ON A.DIRECTORID = B.DIRECTORID
WHERE INDUSTRY = 'Tollywood' GROUP BY A.DIRECTOR ORDER BY TTL_IG_COLLECTION DESC LIMIT 3;

# 69) Write a query to get top 3 directors based on India gross collections in Kollywood industry?
SELECT A.DIRECTOR, SUM(B.INDIA_GROSS_COLLECTION) TTL_IG_COLLECTION FROM DIRECTOR A JOIN BOXOFFICE B ON A.DIRECTORID = B.DIRECTORID
WHERE INDUSTRY = 'Kollywood' GROUP BY A.DIRECTOR ORDER BY TTL_IG_COLLECTION DESC LIMIT 3;

# 70) Write a query to get top 3 directors based on India gross collections in Mollywood industry?
SELECT A.DIRECTOR, SUM(B.INDIA_GROSS_COLLECTION) TTL_IG_COLLECTION FROM DIRECTOR A JOIN BOXOFFICE B ON A.DIRECTORID = B.DIRECTORID
WHERE INDUSTRY = 'Mollywood' GROUP BY A.DIRECTOR ORDER BY TTL_IG_COLLECTION DESC LIMIT 3;

# 71) Write a query to get top 3 directors based on India gross collections in Sandalwood industry?
SELECT A.DIRECTOR, SUM(B.INDIA_GROSS_COLLECTION) TTL_IG_COLLECTION FROM DIRECTOR A JOIN BOXOFFICE B ON A.DIRECTORID = B.DIRECTORID
WHERE INDUSTRY = 'Sandalwood' GROUP BY A.DIRECTOR ORDER BY TTL_IG_COLLECTION DESC LIMIT 3;

# 72) Write to get total number of genres? 
SELECT COUNT(DISTINCT GENREID) TTL_GENRES FROM GENRE;

# 73) Write query to get director, language, genre films count? 
SELECT A.DIRECTOR, B.LANGUAGE, C.GENRE, COUNT(D.TITLE) FROM BOXOFFICE D, DIRECTOR A, LANGUAGE B, GENRE C 
WHERE A.DIRECTORID = D.DIRECTORID AND B.LANGUAGEID = D.LANGUAGEID AND C.GENREID = D.GENREID 
GROUP BY A.DIRECTOR, B.LANGUAGE, C.GENRE ORDER BY A.DIRECTOR, B.LANGUAGE, C.GENRE;

# 74) Write a query to genre wise budget? 
SELECT A.GENRE, SUM(B.BUDGET) TTL_BUDGET FROM GENRE A JOIN BOXOFFICE B ON A.GENREID = B.GENREID GROUP BY A.GENRE ORDER BY A.GENRE;

# 75) Write a query to get genre wise first day worldwide collections? 
SELECT A.GENRE, SUM(B.FIRST_DAY_COLLECTION_WORLDWIDE) TTL_FDWW_COLLECTION FROM GENRE A JOIN BOXOFFICE B ON A.GENREID = B.GENREID 
GROUP BY A.GENRE ORDER BY A.GENRE;

# 76) Write a query to get genre wise overseas collections? 
SELECT A.GENRE, SUM(B.OVERSEAS_COLLECTION) TTL_OVERSEAS_COLLECTION FROM GENRE A JOIN BOXOFFICE B ON A.GENREID = B.GENREID 
GROUP BY A.GENRE ORDER BY A.GENRE;

# 77) Write a query to get genre wise India gross collections? 
SELECT A.GENRE, SUM(B.INDIA_GROSS_COLLECTION) TTL_IG_COLLECTION FROM GENRE A JOIN BOXOFFICE B ON A.GENREID = B.GENREID 
GROUP BY A.GENRE ORDER BY A.GENRE;

# 78) Write a query to get genre wise top 2 longest run time movies? 
SELECT * FROM (SELECT A.GENRE, B.TITLE, B.RUNTIME_MINS, RANK() OVER(PARTITION BY A.GENRE ORDER BY B.RUNTIME_MINS DESC) AS RNK
FROM GENRE A JOIN BOXOFFICE B ON A.GENREID = B.GENREID) A WHERE RNK <= 2;

# 79) Write a query to get genre wise bottom shortest runtime movies? 
SELECT GENRE, TITLE, RUNTIME_MINS FROM (SELECT A.GENRE, B.TITLE, B.RUNTIME_MINS, RANK() OVER(PARTITION BY A.GENRE 
ORDER BY B.RUNTIME_MINS ASC) AS RNK FROM GENRE A JOIN BOXOFFICE B ON A.GENREID = B.GENREID) A WHERE RNK <= 1;

# 80) Write a query to get verdict, genre wise films released? 
SELECT A.VERDICT, B.GENRE, COUNT(A.TITLE) TTL_FILMS FROM BOXOFFICE A JOIN GENRE B ON A.GENREID = B.GENREID 
GROUP BY A.VERDICT, B.GENRE ORDER BY A.VERDICT, B.GENRE;

# 81) Write a query to get genre, OTT platform wise films count? 
SELECT A.GENRE, B.OTT_PLATFORM, COUNT(B.TITLE) TTL_FILMS FROM GENRE A JOIN BOXOFFICE B ON A.GENREID = B.GENREID
GROUP BY A.GENRE, B.OTT_PLATFORM ORDER BY A.GENRE, B.OTT_PLATFORM;

# 82) Write a query to get genre wise films count? 
SELECT A.GENRE, COUNT(B.TITLE) TTL_FILMS FROM GENRE A JOIN BOXOFFICE B ON A.GENREID = B.GENREID GROUP BY A.GENRE ORDER BY A.GENRE;

# 83) Write a query to get genre wise films count in Tollywood Industry? 
SELECT A.GENRE, COUNT(B.TITLE) TTL_FILMS FROM GENRE A JOIN BOXOFFICE B ON A.GENREID = B.GENREID 
WHERE INDUSTRY = 'Tollywood' GROUP BY A.GENRE ORDER BY A.GENRE;

# 84) Write a query to get genre wise films count in Kollywood Industry? 
SELECT A.GENRE, COUNT(B.TITLE) TTL_FILMS FROM GENRE A JOIN BOXOFFICE B ON A.GENREID = B.GENREID 
WHERE INDUSTRY = 'Kollywood' GROUP BY A.GENRE ORDER BY A.GENRE;

# 85) Write a query to get genre wise films count in Mollywood Industry? 
SELECT A.GENRE, COUNT(B.TITLE) TTL_FILMS FROM GENRE A JOIN BOXOFFICE B ON A.GENREID = B.GENREID 
WHERE INDUSTRY = 'Mollywood' GROUP BY A.GENRE ORDER BY A.GENRE;

# 86) Write a query to get genre wise films count in Bollywood Industry? 
SELECT A.GENRE, COUNT(B.TITLE) TTL_FILMS FROM GENRE A JOIN BOXOFFICE B ON A.GENREID = B.GENREID 
WHERE INDUSTRY = 'Bollywood' GROUP BY A.GENRE ORDER BY A.GENRE;

# 87) Write a query to get genre wise films count in Sandalwood Industry? 
SELECT A.GENRE, COUNT(B.TITLE) TTL_FILMS FROM GENRE A JOIN BOXOFFICE B ON A.GENREID = B.GENREID 
WHERE INDUSTRY = 'Sandalwood' GROUP BY A.GENRE ORDER BY A.GENRE;

# 88) Write a query to get lead actors/actress wise, genre and films count? 
SELECT A.LEAD_ACTOR_ACTRESS, B.GENRE, COUNT(A.TITLE) TTL_FILMS FROM BOXOFFICE A JOIN GENRE B ON A.GENREID = B.GENREID
GROUP BY A.LEAD_ACTOR_ACTRESS, B.GENRE ORDER BY A.LEAD_ACTOR_ACTRESS, B.GENRE;

# 89) Write a query to get 5th rank movie based on Worldwide total collections? 
SELECT TITLE, WORLDWIDE_COLLECTION FROM (SELECT TITLE, WORLDWIDE_COLLECTION, RANK() OVER(ORDER BY 
WORLDWIDE_COLLECTION DESC) AS RNK FROM BOXOFFICE) A WHERE RNK = 5;

# 90) Write a query to get 5th rank movie by industry wise based on First day worldwide collections?
SELECT INDUSTRY, TITLE, FIRST_DAY_COLLECTION_WORLDWIDE FROM (SELECT INDUSTRY, TITLE, FIRST_DAY_COLLECTION_WORLDWIDE, RANK()
OVER(PARTITION BY INDUSTRY ORDER BY FIRST_DAY_COLLECTION_WORLDWIDE DESC) AS RNK FROM BOXOFFICE) A WHERE RNK = 5;

# 91) Write a query to get 3rd rank movie by industry wise based on IMDb Ratings? 
SELECT INDUSTRY, TITLE, IMDB_RATING FROM (SELECT INDUSTRY, TITLE, IMDB_RATING, RANK() OVER(PARTITION BY INDUSTRY 
ORDER BY IMDB_RATING DESC) AS RNK FROM BOXOFFICE) A WHERE RNK = 3;

# 92) Write a stored procedure to get top 5 films based on India gross collections? 
DELIMITER $$
CREATE PROCEDURE GETTOP5IGCOL() 
BEGIN
	SELECT TITLE, INDIA_GROSS_COLLECTION FROM BOXOFFICE ORDER BY INDIA_GROSS_COLLECTION DESC LIMIT 5;
END
$$

CALL GETTOP5IGCOL();

# 93) Write a stored procdure to get industry Budget and Worldwide total collections? If we call any industry it will display industry, budget and wordwide total 
DELIMITER $$
CREATE PROCEDURE GETINDBUDWWTOTAL(IN INDUS VARCHAR(20))
BEGIN
	SELECT INDUSTRY, SUM(BUDGET) TTL_BUDGET, SUM(WORLDWIDE_COLLECTION) TTL_WW_COLLECTION FROM BOXOFFICE WHERE INDUSTRY = INDUS
    GROUP BY INDUSTRY;
END
$$

CALL GETINDBUDWWTOTAL('Tollywood');
CALL GETINDBUDWWTOTAL('Bollywood');

# 94) Calculate YoY% Budget growth? 
WITH BUDGET_DATA AS (SELECT YEAR, SUM(BUDGET) TTL_BUDGET FROM BOXOFFICE GROUP BY YEAR ORDER BY YEAR)
SELECT A.YEAR, A.TTL_BUDGET, ROUND(((A.TTL_BUDGET - B.TTL_BUDGET) / B.TTL_BUDGET) * 100, 2) AS YoY_GROWTH_PERCENTAGE
FROM BUDGET_DATA A LEFT JOIN BUDGET_DATA B ON A.YEAR = B.YEAR + 1 ORDER BY B.YEAR;

# 95) Calculate YoY% Worldwide total collections growth? 
WITH WWC_DATA AS (SELECT YEAR, SUM(WORLDWIDE_COLLECTION) TTL_WWC FROM BOXOFFICE GROUP BY YEAR ORDER BY YEAR)
SELECT A.YEAR, A.TTL_WWC, ROUND(((A.TTL_WWC - B.TTL_WWC) / B.TTL_WWC) * 100, 2) AS YoY_GROWTH_PERCENTAGE
FROM WWC_DATA A LEFT JOIN WWC_DATA B ON A.YEAR = B.YEAR + 1 ORDER BY B.YEAR;

# 96) Calculate YoY% Indian Gross collections growth? 
WITH IGC_DATA AS (SELECT YEAR, SUM(INDIA_GROSS_COLLECTION) TTL_IGC FROM BOXOFFICE GROUP BY YEAR ORDER BY YEAR)
SELECT A.YEAR, A.TTL_IGC, ROUND(((A.TTL_IGC - B.TTL_IGC) / B.TTL_IGC) * 100, 2) AS YoY_GROWTH_PERCENTAGE
FROM IGC_DATA A LEFT JOIN IGC_DATA B ON A.YEAR = B.YEAR + 1 ORDER BY B.YEAR;

# 97) Create a stored procedure to get Total films count, world wide total collections? 
DELIMITER $$
CREATE PROCEDURE GETTTLFILMWWC()
BEGIN
	SELECT COUNT(TITLE) TTL_FILMS, SUM(WORLDWIDE_COLLECTION) TTL_WW_COLLECTION FROM BOXOFFICE;
END
$$

CALL GETTTLFILMWWC()